mysql:
    image: mysql
    restart: always
    mem_limit: 2147483648
    ports:
        - "3306:3306"
    environment:
        - MYSQL_RANDOM_ROOT_PASSWORD=true
        - MYSQL_USER=airflow
        - MYSQL_PASSWORD=airflow
        - MYSQL_DATABASE=airflow

webserver:
    links:
        - mysql:mysql

scheduler:
    links:
        - mysql:mysql

worker:
    links:
        - mysql:mysql

flower:
    links:
        - mysql:mysql
