mysql:
    image: mysql
    restart: always
    mem_limit: 2147483648
    ports:
        - "3306:3306"
    environment:
        - MYSQL_RANDOM_ROOT_PASSWORD=true
        - MYSQL_USER=airflow
        - MYSQL_PASSWORD=airflow
        - MYSQL_DATABASE=airflow

rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
        - "15672:15672"
        - "5672:5672"
    environment:
        - RABBITMQ_DEFAULT_USER=airflow
        - RABBITMQ_DEFAULT_PASS=airflow
        - RABBITMQ_DEFAULT_VHOST=airflow

webserver:
    image: vitillo/telemetry-airflow
    restart: always
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
        - AIRFLOW_ENABLE_AUTH
        - AWS_REGION
        - EMR_KEY_NAME
        - EMR_RELEASE_LABEL
        - EMR_FLOW_ROLE
        - EMR_SERVICE_ROLE
        - EMR_INSTANCE_TYPE
        - SPARK_BUCKET
        - AIRFLOW_BUCKET
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - DB_URI
        - DB_USER
        - DB_PASSWORD
    ports:
        - "8080:8080"
    links:
        - mysql:mysql
        - rabbitmq:rabbitmq
        - worker:worker
        - scheduler:scheduler
    command: webserver

flower:
    image: vitillo/telemetry-airflow
    restart: always
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
        - AIRFLOW_ENABLE_AUTH
        - AWS_REGION
        - EMR_KEY_NAME
        - EMR_RELEASE_LABEL
        - EMR_FLOW_ROLE
        - EMR_SERVICE_ROLE
        - EMR_INSTANCE_TYPE
        - SPARK_BUCKET
        - AIRFLOW_BUCKET
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - DB_URI
        - DB_USER
        - DB_PASSWORD
    ports:
        - "5555:5555"
    links:
        - rabbitmq:rabbitmq
    command: flower

scheduler:
    image: vitillo/telemetry-airflow
    restart: always
    mem_limit: 2147483648
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
        - AIRFLOW_ENABLE_AUTH
        - AWS_REGION
        - EMR_KEY_NAME
        - EMR_RELEASE_LABEL
        - EMR_FLOW_ROLE
        - EMR_SERVICE_ROLE
        - EMR_INSTANCE_TYPE
        - SPARK_BUCKET
        - AIRFLOW_BUCKET
        - COMMAND
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - DB_URI
        - DB_USER
        - DB_PASSWORD
    links:
        - mysql:mysql
        - rabbitmq:rabbitmq

worker:
    image: vitillo/telemetry-airflow
    restart: always
    mem_limit: 2147483648
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
    ports:
        - "8793:8793"
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
        - AIRFLOW_ENABLE_AUTH
        - AWS_REGION
        - EMR_KEY_NAME
        - EMR_RELEASE_LABEL
        - EMR_FLOW_ROLE
        - EMR_SERVICE_ROLE
        - EMR_INSTANCE_TYPE
        - SPARK_BUCKET
        - AIRFLOW_BUCKET
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - DB_URI
        - DB_USER
        - DB_PASSWORD
    links:
        - mysql:mysql
        - rabbitmq:rabbitmq
    command: worker
