region: us-west-2
airflow_bucket: telemetry-test-bucket
spark_bucket: telemetry-spark-emr-2

emr_key_name: mozilla_vitillo
emr_release_label: emr-4.3.0
emr_flow_role: telemetry-spark-cloudformation-TelemetrySparkInstanceProfile-1SATUBVEXG7E3
emr_service_role: EMR_DefaultRole
emr_instance_type: c3.4xlarge

ecs_sg_name: telemetry-ecs
ecs_key_name: mozilla_vitillo
ecs_vpc_id: vpc-4283d227
ecs_vpc_subnet_id: subnet-125a7c77
ecs_cluster_name: telemetry
ecs_instance_type: c4.2xlarge 
ecs_role: arn:aws:iam::927034868273:role/telemetry-ecs-cloudformation-TelemetryECSRole-1UAYK6XNB6DG0

db_uri: mysql
db_user: airflow
db_password: airflow
