- name: deploy Airflow container locally
  hosts: localhost

  tasks:
    - name: launch Airflow containers
      shell: "{{ item }}"
      with_items:
        - docker-compose -f ansible/files/docker-compose-test.yml stop
        - docker-compose -f ansible/files/docker-compose-test.yml rm -fav
        - docker-compose -f ansible/files/docker-compose-test.yml up -d
      environment:
        REGION: "{{ region }}"
        EMR_KEY_NAME: "{{ emr_key_name }}"
        EMR_RELEASE_LABEL: "{{ emr_release_label }}"
        EMR_FLOW_ROLE: "{{ emr_flow_role }}"
        EMR_SERVICE_ROLE: "{{ emr_service_role }}"
        EMR_INSTANCE_TYPE: "{{ emr_instance_type }}"
        SPARK_BUCKET: "{{ spark_bucket }}"
        AIRFLOW_BUCKET: "{{ airflow_bucket }} "
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        COMMAND: test {{ dag }} {{ task }} {{ date }}
